baseurl: /publishing/groups/epub-wg
groupid: 125377
charter: /2020/08/epub-wg-charter.html
wgname_lc: epub
wgname_uc: EPUB 3
github: https://github.com/w3c/epub-wg/
extra_call_id: epub-topic
mission: "maintain and develop the EPUB 3 family of specifications, to represent the EPUB community in the W3C, and to support EPUB 3 content creators and consumers by further advancing, refining, and clarifying the current EPUB 3 specification."



#theme: jekyll-theme-minimal
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - node_modules/

collections:
  minutes:
    output: true
    permalink: /Meetings/Minutes/:name
